	-- ===============================================
-- DATABASE: Courier Tracking System
-- ===============================================

-- ===============================================
-- 1. CUSTOMER TABLE
-- ===============================================
CREATE TABLE Customer (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Phone VARCHAR2(15) UNIQUE NOT NULL
);

-- ===============================================
-- 2. PARCEL TABLE
-- ===============================================
CREATE TABLE Parcel (
    ParcelID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TrackingID VARCHAR2(20) UNIQUE NOT NULL,
    SenderID NUMBER NOT NULL,
    ReceiverID NUMBER NOT NULL,
    CurrentStatus VARCHAR2(50) DEFAULT 'Booked',
    FOREIGN KEY (SenderID) REFERENCES Customer(CustomerID),
    FOREIGN KEY (ReceiverID) REFERENCES Customer(CustomerID)
);

-- ===============================================
-- 3. CHECKPOINT TABLE
-- ===============================================
CREATE TABLE Checkpoint (
    CheckpointID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ParcelID NUMBER NOT NULL,
    Location VARCHAR2(100) NOT NULL,
    Status VARCHAR2(50) NOT NULL,
    UpdateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ParcelID) REFERENCES Parcel(ParcelID)
);

-- ===============================================
-- 4. ROUTE TABLE
-- ===============================================
CREATE TABLE Route (
    RouteID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ParcelID NUMBER NOT NULL,
    StartLocation VARCHAR2(100) NOT NULL,
    EndLocation VARCHAR2(100) NOT NULL,
    EstimatedDelivery DATE,
    FOREIGN KEY (ParcelID) REFERENCES Parcel(ParcelID)
);

-- ===============================================
-- 5. TRIGGER: Auto-update Parcel.CurrentStatus
-- ===============================================
CREATE OR REPLACE TRIGGER trg_update_parcel_status
AFTER INSERT ON Checkpoint
FOR EACH ROW
BEGIN
    UPDATE Parcel
    SET CurrentStatus = :NEW.Status
    WHERE ParcelID = :NEW.ParcelID;
END;
/

-- ===============================================
-- 6. SAMPLE DATA: CUSTOMERS
-- ===============================================
INSERT INTO Customer (Name, Email, Phone) VALUES ('Thavasi', 'thavasi@email.com', '9876543210');
INSERT INTO Customer (Name, Email, Phone) VALUES ('Akshini', 'akshini@email.com', '9876501234');

-- ===============================================
-- 7. SAMPLE DATA: PARCELS
-- ===============================================
INSERT INTO Parcel (TrackingID, SenderID, ReceiverID) VALUES ('TRK1001', 1, 2);
INSERT INTO Parcel (TrackingID, SenderID, ReceiverID) VALUES ('TRK1002', 2, 1);

-- ===============================================
-- 8. SAMPLE DATA: CHECKPOINTS (Parcel 1)
-- ===============================================
INSERT INTO Checkpoint (ParcelID, Location, Status) VALUES (1, 'Mumbai Hub', 'Order Placed');
INSERT INTO Checkpoint (ParcelID, Location, Status) VALUES (1, 'Mumbai Sorting Center', 'Picked Up');
INSERT INTO Checkpoint (ParcelID, Location, Status) VALUES (1, 'Pune Transit Hub', 'In Transit');
INSERT INTO Checkpoint (ParcelID, Location, Status) VALUES (1, 'Bangalore Distribution Center', 'In Transit');
INSERT INTO Checkpoint (ParcelID, Location, Status) VALUES (1, 'Bangalore - Delivery Zone 3', 'Out for Delivery');
INSERT INTO Checkpoint (ParcelID, Location, Status) VALUES (1, 'Customer Address', 'Delivered');

-- ===============================================
-- 9. SAMPLE DATA: CHECKPOINTS (Parcel 2)
-- ===============================================
INSERT INTO Checkpoint (ParcelID, Location, Status) VALUES (2, 'Chennai Hub', 'Order Placed');
INSERT INTO Checkpoint (ParcelID, Location, Status) VALUES (2, 'Chennai Sorting Center', 'Picked Up');
INSERT INTO Checkpoint (ParcelID, Location, Status) VALUES (2, 'Bangalore Transit Hub', 'In Transit');
INSERT INTO Checkpoint (ParcelID, Location, Status) VALUES (2, 'Bangalore Delivery Zone 2', 'Out for Delivery');
INSERT INTO Checkpoint (ParcelID, Location, Status) VALUES (2, 'Receiver Address', 'Delivered');

-- ===============================================
-- 10. SAMPLE DATA: ROUTES
-- ===============================================
INSERT INTO Route (ParcelID, StartLocation, EndLocation, EstimatedDelivery) 
VALUES (1, 'Mumbai Hub', 'Bangalore Delivery Zone 3', TO_DATE('2025-10-23', 'YYYY-MM-DD'));

INSERT INTO Route (ParcelID, StartLocation, EndLocation, EstimatedDelivery) 
VALUES (2, 'Chennai Hub', 'Receiver Address', TO_DATE('2025-10-24', 'YYYY-MM-DD'));

-- ===============================================
-- 11. UI DESIGN NOTES FOR REFERENCE
-- ===============================================
-- Interface should show a vertical tracking timeline:
-- Delivered (green), Out for Delivery (yellow/orange), In Transit (yellow/orange),
-- Picked Up (blue), Order Placed (gray)
-- Title bar: 'Tracking Timeline'
-- Clean white background, soft gray borders, readable modern font
